// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectCondoManagement.Data.Entites.CondosDb;

#nullable disable

namespace ProjectCondoManagement.Migrations.CondosDb
{
    [DbContext(typeof(DataContextCondos))]
    [Migration("20250823182906_FinancialAccountToCondominium")]
    partial class FinancialAccountToCondominium
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CondoMemberMeeting", b =>
                {
                    b.Property<int>("CondoMembersId")
                        .HasColumnType("int");

                    b.Property<int>("MeetingsAttendedId")
                        .HasColumnType("int");

                    b.HasKey("CondoMembersId", "MeetingsAttendedId");

                    b.HasIndex("MeetingsAttendedId");

                    b.ToTable("CondoMemberMeeting");
                });

            modelBuilder.Entity("CondoMemberUnit", b =>
                {
                    b.Property<int>("CondoMembersId")
                        .HasColumnType("int");

                    b.Property<int>("UnitsId")
                        .HasColumnType("int");

                    b.HasKey("CondoMembersId", "UnitsId");

                    b.HasIndex("UnitsId");

                    b.ToTable("CondoMemberUnit");
                });

            modelBuilder.Entity("OccurrenceUnit", b =>
                {
                    b.Property<int>("OccurrencesId")
                        .HasColumnType("int");

                    b.Property<int>("UnitsId")
                        .HasColumnType("int");

                    b.HasKey("OccurrencesId", "UnitsId");

                    b.HasIndex("UnitsId");

                    b.ToTable("OccurrenceUnit");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.CondoMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<string>("ConduminiumId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.ToTable("CondoMembers");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Condominium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CondoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FinancialAccountId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Condominiums");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MeetingType")
                        .HasColumnType("bit");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.HasIndex("ReportId");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Occurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Meeting")
                        .HasColumnType("int");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.HasIndex("MeetingId");

                    b.ToTable("Occurences");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<string>("Door")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondoMemberId")
                        .HasColumnType("int");

                    b.Property<int?>("VotingId")
                        .HasColumnType("int");

                    b.Property<bool>("YesNoVote")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CondoMemberId");

                    b.HasIndex("VotingId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Voting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Matter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeetingId")
                        .HasColumnType("int");

                    b.Property<bool>("Result")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("Voting");
                });

            modelBuilder.Entity("CondoMemberMeeting", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.CondoMember", null)
                        .WithMany()
                        .HasForeignKey("CondoMembersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingsAttendedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CondoMemberUnit", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.CondoMember", null)
                        .WithMany()
                        .HasForeignKey("CondoMembersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OccurrenceUnit", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Occurrence", null)
                        .WithMany()
                        .HasForeignKey("OccurrencesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.CondoMember", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Condominium", "Condominium")
                        .WithMany("CondoMembers")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condominium");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Document", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Condominium", null)
                        .WithMany("Documents")
                        .HasForeignKey("CondominiumId");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Meeting", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Condominium", "Condominium")
                        .WithMany("Meetings")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Document", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condominium");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Occurrence", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Condominium", null)
                        .WithMany("Occurrences")
                        .HasForeignKey("CondominiumId");

                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Meeting", null)
                        .WithMany("Occurences")
                        .HasForeignKey("MeetingId");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Unit", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Condominium", "Condominium")
                        .WithMany("Units")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condominium");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Vote", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.CondoMember", "CondoMember")
                        .WithMany()
                        .HasForeignKey("CondoMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Voting", null)
                        .WithMany("Votes")
                        .HasForeignKey("VotingId");

                    b.Navigation("CondoMember");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Voting", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.CondosDb.Meeting", "Meeting")
                        .WithMany("Votings")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Condominium", b =>
                {
                    b.Navigation("CondoMembers");

                    b.Navigation("Documents");

                    b.Navigation("Meetings");

                    b.Navigation("Occurrences");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Meeting", b =>
                {
                    b.Navigation("Occurences");

                    b.Navigation("Votings");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.CondosDb.Voting", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
