// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectCondoManagement.Data.Entites.FinancesDb;

#nullable disable

namespace ProjectCondoManagement.Migrations.FinancesDb
{
    [DbContext(typeof(DataContextFinances))]
    [Migration("20250829175042_PaymentExternal")]
    partial class PaymentExternal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.FinancesDb.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.FinancesDb.FinancialAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssociatedBankAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FinancialAccounts");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.FinancesDb.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("BeneficiaryAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("BeneficiaryFinancialAccountId")
                        .HasColumnType("int");

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<int?>("PayerAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("PayerFinancialAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryFinancialAccountId");

                    b.HasIndex("PayerFinancialAccountId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.FinancesDb.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalRecipientBankAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OneTimeExpenseId")
                        .HasColumnType("int");

                    b.Property<int>("PayerFinancialAccountId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OneTimeExpenseId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.FinancesDb.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("BeneficiaryAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PayerAccountId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryAccountId");

                    b.HasIndex("PayerAccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.FinancesDb.Expense", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.FinancesDb.Payment", null)
                        .WithMany("Expenses")
                        .HasForeignKey("PaymentId");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.FinancesDb.Invoice", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.FinancesDb.FinancialAccount", "BeneficiaryFinancialAccount")
                        .WithMany()
                        .HasForeignKey("BeneficiaryFinancialAccountId");

                    b.HasOne("ProjectCondoManagement.Data.Entites.FinancesDb.Payment", "Payment")
                        .WithOne("Invoice")
                        .HasForeignKey("ProjectCondoManagement.Data.Entites.FinancesDb.Invoice", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectCondoManagement.Data.Entites.FinancesDb.FinancialAccount", "PayerFinancialAccount")
                        .WithMany()
                        .HasForeignKey("PayerFinancialAccountId");

                    b.Navigation("BeneficiaryFinancialAccount");

                    b.Navigation("PayerFinancialAccount");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.FinancesDb.Payment", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.FinancesDb.Expense", "OneTimeExpense")
                        .WithMany()
                        .HasForeignKey("OneTimeExpenseId");

                    b.Navigation("OneTimeExpense");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.FinancesDb.Transaction", b =>
                {
                    b.HasOne("ProjectCondoManagement.Data.Entites.FinancesDb.FinancialAccount", "AccountBeneficiary")
                        .WithMany("TransactionsAsBeneficiary")
                        .HasForeignKey("BeneficiaryAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectCondoManagement.Data.Entites.FinancesDb.Payment", "Payment")
                        .WithOne("Transaction")
                        .HasForeignKey("ProjectCondoManagement.Data.Entites.FinancesDb.Transaction", "Id");

                    b.HasOne("ProjectCondoManagement.Data.Entites.FinancesDb.FinancialAccount", "AccountPayer")
                        .WithMany("TransactionsAsPayer")
                        .HasForeignKey("PayerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountBeneficiary");

                    b.Navigation("AccountPayer");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.FinancesDb.FinancialAccount", b =>
                {
                    b.Navigation("TransactionsAsBeneficiary");

                    b.Navigation("TransactionsAsPayer");
                });

            modelBuilder.Entity("ProjectCondoManagement.Data.Entites.FinancesDb.Payment", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Invoice");

                    b.Navigation("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
